version: '3'

services:
  dynamo:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - dynamo_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."

volumes:
  dynamo_data: